bash tests/tests-sh/test-p3-1-1.sh
bash tests/tests-sh/test-p3-1-2.sh
bash tests/tests-sh/test-p3-2-1.sh
bash tests/tests-sh/test-p3-2-2.sh
bash tests/tests-sh/test-p3-2-3.sh
bash tests/tests-sh/test-p3-2-4.sh
bash tests/tests-sh/test-p3-2-5.sh
bash tests/tests-sh/test-p3-3-1.sh
bash tests/tests-sh/test-p3-3-2.sh
bash tests/tests-sh/test-p3-3-3.sh
bash tests/tests-sh/test-p3-3-4.sh
bash tests/tests-sh/test-p3-3-5.sh
bash tests/tests-sh/test-p3-4-1.sh
bash tests/tests-sh/test-p3-4-2.sh
bash tests/tests-sh/test-p3-4-3.sh
bash tests/tests-sh/test-p3-4-4.sh
bash tests/tests-sh/test-p3-4-5.sh
bash tests/tests-sh/test-p3-4-6.sh
bash tests/tests-sh/test-p3-4-7.sh
bash tests/tests-sh/test-p3-4-8.sh
bash tests/tests-sh/test-p3-4-9.sh
bash tests/tests-sh/test-p3-4-10.sh
bash tests/tests-sh/test-p3-4-11.sh
bash tests/tests-sh/test-p3-4-12.sh
bash tests/tests-sh/test-p3-5-1.sh
bash tests/tests-sh/test-p3-6-1.sh
bash tests/tests-sh/test-p3-7-1.sh
bash tests/tests-sh/test-p3-7-2.sh
bash tests/tests-sh/test-p3-7-3.sh
bash tests/tests-sh/test-p3-8-1.sh
bash tests/tests-sh/test-p3-8-2.sh
bash tests/tests-sh/test-p3-8-3.sh
bash tests/tests-sh/test-p3-9-1.sh